--- #YAML:1.0
name:                BerkeleyDB
version:             0.32
abstract:            Perl extension for Berkeley DB version 2, 3 or 4
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.34
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Paul Marquess <pmqs@cpan.org>
